### ISSUE TITLE
Dynamic color theming not working in separate style sheet

### ISSUE THREAD

**Issue by saisrirammanchella** [Ladekarl/react-native-color-theme#1]
hi,
    react-native-color-theme: "0.0.1",
    react-native: "0.50.4",
   The problem is when i apply this colors in inline styles, color theming was working but when i m using in common styles files dynamic changing of themes not working. Can anyone help on this.
<img width="1109" alt="screen shot 2017-11-29 at 11 53 55 am" src="https://user-images.githubusercontent.com/25579546/33361135-d087d166-d4fc-11e7-8ee8-042dd57fbaf6.png">
<img width="954" alt="screen shot 2017-11-29 at 11 54 16 am" src="https://user-images.githubusercontent.com/25579546/33361136-d2a07c14-d4fc-11e7-99ac-a3e826786316.png">
<img width="1083" alt="screen shot 2017-11-29 at 11 54 26 am" src="https://user-images.githubusercontent.com/25579546/33361143-d511a270-d4fc-11e7-8940-9fac41542123.png">

**Comment by Ladekarl** [comment]
Hi @saisrirammanchella 

Thank you for using the theme manager.

If you would like to use dynamic styling you should supply a function to the style instead just as you would do in any case when using dynamic styling. 
This way the styling will get updated every time react native renders the application. Otherwise it will only get updated when the `styles` constant is reevaluated. I added an example project that you can look into here [example/App.js](https://github.com/Ladekarl/react-native-color-theme/blob/master/example/App.js)
